on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing GitHub"
        run: echo "Hello from GitHub Actions"

      - uses: action/checkout@v3
      
      - name: 'printing folder contents'
        run: ls
      
      # - name: "login docker hub"
      #   run: docker login --username 
      # - name: "build image"
      #   run: docker build -t 


