on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing GitHub"
        run: echo "Hello from GitHub Actions"

      - name: 'printing folder contents_before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'printing folder contents_after'
        run: ls -a
      
      - name: "login to docker hub"
        run: docker login --username ${{ secrets.USER_NAME }} --password ${{ secrets.TOKEN }}
   


